language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore Xabe.FileLock.Test/
 - dotnet test Xabe.FileLock.Test/
 - dotnet restore Xabe.FileLock/
 - dotnet build Xabe.FileLock/ -c Release
