language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore Xabe.FileLock.Test/
 - dotnet test Xabe.FileLock.Test/
 - dotnet restore Xabe.FileLock/
 - dotnet build Xabe.FileLock/ -c Release
 - dotnet pack Xabe.FileLock -c Release -o nuget /p:PackageVersion=$TRAVIS_TAG
 - dotnet nuget push Xabe.FileLock/nuget/*.nupkg -k $NUGET_API -s https://www.nuget.org/api/v2/package 
